### ISSUE TITLE
2nd Operation on .win file crashes uQlx

### ISSUE THREAD

**Issue by xXorAa** [SinclairQL/uqlx-fork#1]
Starting program: /home/graeme/Work/uqlx-fork/qm 
problem, stat failed : No such file or directory
 - MountPoint /dev/fd0 for device FLP1_ may not be accessible
*** QL Emulator v0.50 ***
release 2012-07-26

Program received signal SIGSEGV, Segmentation fault.
FileAlreadyOpen (drive=<optimized out>, filesys=<optimized out>, fileNum=..., perm=perm@entry=0x7fffffffe45c) at QL_files.c:818
818           if(GET_OPEN(f) && (GET_ISDISK(f)==1) && 
(gdb) bt
#0  FileAlreadyOpen (drive=<optimized out>, filesys=<optimized out>, fileNum=..., perm=perm@entry=0x7fffffffe45c) at QL_files.c:818
#1  0x000000000041ce19 in QDiskOpen (f=f@entry=0x7ffff68ebd7e, drive=drive@entry=0, canExist=canExist@entry=1 '\001', canCreate=<optimized out>) at QDisk.c:2096
#2  0x0000000000417ba8 in mdv_doopen (f=f@entry=0x7ffff68ebd7e, filesys=filesys@entry=1, drive=0, drive@entry=1, key=1, pdb=<optimized out>) at QL_files.c:617
#3  0x0000000000418176 in MdvOpen () at QL_files.c:730
#4  0x00000000004252b0 in ExecuteLoop () at instructions_ao.c:2549
#5  0x000000000042c398 in ExecuteChunk (n=n@entry=3000) at iexl_general.c:795
#6  0x0000000000433152 in QLRun () at unixstuff.c:1151
#7  0x000000000040455a in main (ac=<optimized out>, av=<optimized out>) at xlmain.c:39

**Comment by xXorAa** [comment]
Fixed by commit
