### ISSUE TITLE
Race Condition crashes in qvfs_test

### ISSUE THREAD

**Issue by xXorAa** [SinclairQL/uqlx-fork#6]
```
10 LRESPR mdv1_ptr_gen
20 EX mdv1_xtricator_exe
```

```
Program received signal SIGSEGV, Segmentation fault.
0xf7d24877 in memset () from /lib/libc.so.6
Missing separate debuginfos, use: dnf debuginfo-install libX11-1.6.5-7.fc28.i686 libXau-1.0.8-11.fc28.i686 libXcursor-1.1.15-1.fc28.i686 libXext-1.3.3-8.fc28.i686 libXfixes-5.0.3-5.fc28.i686 libXrender-0.9.10-5.fc28.i686 libxcb-1.13-1.fc28.i686
(gdb) bt
#0  0xf7d24877 in memset () from /lib/libc.so.6
#1  0xf7d2331e in strncpy () from /lib/libc.so.6
#2  0x08073254 in qvf_test (id=10, name=0xf786a22c "\200") at QVFS.c:71
#3  0x0805eef5 in DrvOpen () at QL_driver.c:467
#4  0x0806f2c9 in ExecuteLoop () at instructions_ao.c:2549
#5  0x0807308f in ExecuteChunk (n=3000) at iexl_general.c:795
#6  0x08079f65 in QLRun () at unixstuff.c:1160
#7  0x0804afcb in main (ac=1, av=0xffffd094) at xlmain.c:39

````

A short pause between line 10 and 20 like PAUSE 50 will stop the crash.

**Comment by xXorAa** [comment]
Caused by A0 being incorrect. Patch to prevent crash applied but I don't know if A0 problem is uQlx specific.
